

export const properties=[
    {
        id:"1",
        title:"شقة للإيجار",
        status:"للإيجار",
        availability:"متاح",
        type: "شقة",
        district:"حي النقرة- حائل",
        price:"24000",
        area:"120",
        rooms:"3",
        bathrooms:"2",
       images: [
  "/images/property-1.jpg",
  "/images/property-2.jpg",
  "/images/property-3.jpg",
],
        description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
        location: "https://maps.google.com/?q=27.5114,41.7208",
        phone:"9665xxxxxxxxx",
    },
    {
       id: "2",
    title: "شقة للإيجار",
     status:"للإيجار",
     availability:"متاح",
     type: "شقة",
    district: "حي الرصف - حائل",
    price: "28000",
    area: "135", 
    rooms:"3",
    bathrooms:"2",
    images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
    {
        id: "3",
    title: "فيلا للبيع",
     status:"للبيع",
     availability:"متاح",
        type: "فيلا",
    district: "حي النقرة - حائل",
    price: "650000",
    area: "300",
    rooms:"3",
    bathrooms:"2",
     images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
    {
        id: "4",
    title: "أرض للبيع",
     status:"للبيع",
     availability:"متاح",
        type: "أرض",
    district: "حي صبابة - حائل",
    price: "420000",
    area: "500",
    rooms:"3",
    bathrooms:"2",
     images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
    {
        id: "5",
    title: "أرض للبيع",
     status:"للبيع",
     availability:"متاح",
        type: "أرض",
    district: "حي النقرة - حائل",
    price: "420000",
    area: "500",
    rooms:"3",
    bathrooms:"2",
     images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
    {
        id: "6",
    title: "أرض للبيع",
     status:"للبيع",
     availability:"متاح",
        type: "أرض",
    district: "حي الجبل - حائل",
    price: "300000",
    area: "500",
    rooms:"3",
    bathrooms:"2",
     images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
    {
        id: "7",
    title: "فيلا للبيع",
     status:"للبيع",
     availability:"متاح",
        type: "فيلا",
    district: "حي صبابة - حائل",
    price: "1000000",
    area: "500",
    rooms:"3",
    bathrooms:"2",
     images: [
        "/images/property-1.jpg",
        "/images/property-2.jpg",
        "/images/property-3.jpg",
    ],
    description:"بحالة جيدة و عمر العقار 5 سنوات جميع الخدمات متوفرة",
    location: "https://maps.google.com/?q=27.5114,41.7208",
    phone:"9665xxxxxxxxx",
    },
];